### PR TITLE
Add .azure/azureProfile.json and Azure environment variable support

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by stuartpreston** [comment]
Ok, I've had a go at testing various scenarios with this and have uncovered some issues that probably need addressing.  Will try and table the results once I've finished the testing and identify what/where needs to be fixed...

## Testing azure_profile changes
### Clean machine state - PASS

 * with an empty ~/.azure directory

OUTPUT:
```
  * machine[pendev01app99] action converge

    ================================================================================
    Error executing action `converge` on resource 'machine[pendev01app99]'
    ================================================================================

    RuntimeError
    ------------
    Driver azure did not specify a subscription ID, and no default subscription was found.  Have you downloaded the Azure CLI and used `azure account download` and `azure account import` to set up Azure?  Alternately, you can set azure_subscriptions to [ { subscription_id: '...', management_credentials: ... }] in your Chef configuration.
```
---
### Subscription specified but no credentials - PASS

 * with subscription specified in the driver URL in the recipe (with_driver 'azure:9c117323-1f20-444d-82a9-9ee430723ba3')
 * and an empty ~/.azure directory

OUTPUT:
```
  * machine[pendev01app99] action converge 

    ================================================================================
    Error executing action `converge` on resource 'machine[pendev01app99]'
    ================================================================================

    RuntimeError
    ------------
    Driver azure did not specify a subscription ID, and no default subscription was found.  Have you downloaded the Azure CLI and used `azure account download` and `azure account import` to set up Azure?  Alternately, you can set azure_subscriptions to [ { subscription_id: '...', management_credentials: ... }] in your Chef configuration.
```
---
### Subscription specified in driver and azureProfile.json used - PASS

 * with subscription specified in the driver URL in the recipe (with_driver 'azure:9c117323-1f20-444d-82a9-9ee430723ba3')
 * and after importing the subscription and keys (azure_profile method)


```
SPMBP:~ SP$ azure account download
info:    Executing command account download
info:    Launching browser to http://go.microsoft.com/fwlink/?LinkId=254432
help:    Save the downloaded file, then execute the command
help:      account import <file>
info:    account download command OK

SPMBP:~ SP$ azure account import ~/Downloads/Microsoft\ Partner\ Network-Pendrica\ Production-3-29-2015-credentials.publishsettings
info:    Executing command account import
info:    account import command OK
```

OUTPUT:
```
  * machine[pendev01app99] action converge
    - Creating pendev01app99 with image b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB in North Europe...Creating deployment...
Creating cloud service pendricacloud01.
Storage Account pendricastore01 already exists. Skipped...
Deployment in progress...
# # etc.
```

---
### Subscription not specified in driver and azureProfile.json used - FAIL 

 * with subscription not specified in the driver URL in the recipe (i.e. with_driver 'azure')
 * and after importing the subscription and keys (azure_profile method)

```
    ================================================================================
    Error executing action `converge` on resource 'machine[pendev01app99]'
    ================================================================================

    RuntimeError
    ------------
    Driver azure did not specify a subscription ID, and no default subscription was found.  Have you downloaded the Azure CLI and used `azure account download` and `azure account import` to set up Azure?  Alternately, you can set azure_subscriptions to [ { subscription_id: '...', management_credentials: ... }] in your Chef configuration.
```

***I think we need to support this scenario, otherwise we force users to duplicate a subscription_id we can already find ourselves.***
---
### Subscription not specified in driver and management_credentials used via .chef/knife.rb - FAIL (not caught)

 * with subscription not specified in the driver URL in the recipe (i.e. with_driver 'azure')
 * renaming ~/.azure/azureProfile.json to azureProfile.json.old
 * copy my.publishsettings to ~/azure/my.publishsettings
 * setup .chef/knife.rb with additional line like so:

```
azure_subscriptions      [ { management_credentials: '/users/SP/.azure/my.publishsettings' } ]
```

OUTPUT:
```
NoMethodError: machine[pendev01app99] (@recipe_files::/Users/SP/destroy-temp.rb line 5) had an error: NoMethodError: undefined method `[]' for nil:NilClass
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-azure-0.2.1/lib/chef/provisioning/azure_driver/driver.rb:44:in `canonicalize_url'
 ```

***Needs further investigation***

---
### Subscription not specified in driver, and subscription_id and management_credentials used via .chef/knife.rb (.publishsettings) - FAIL (not caught)

 * with subscription not specified in the driver URL in the recipe (i.e. with_driver 'azure')
 * copy my.publishsettings to ~/azure/my.publishsettings
 * setup .chef/knife.rb with additional line like so:

```
azure_subscriptions      [ { subscription_id: '9c117323-1f20-444d-82a9-9ee430723ba3', management_credentials: '/users/SP/.azure/my.publishsettings' } ]
```

OUTPUT:
```
2015-03-29T22:12:00+01:00] INFO: Picked first subscription found as default:  (9c117323-1f20-444d-82a9-9ee430723ba3) from Chef configuration
    ================================================================================
    Error executing action `converge` on resource 'machine[pendev01app99]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `ext' for File:Class
```

STACK (highlights possible issue in Azure-Ruby SDK)
```
SPMBP:chef-repo.pendev SP$ cat /Users/SP/.chef/cache/chef-stacktrace.out
Generated at 2015-03-29 22:12:00 +0100
NoMethodError: machine[pendev01app99] (@recipe_files::/Users/SP/destroy-temp.rb line 5) had an error: NoMethodError: undefined method `ext' for File:Class
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/stuartpreston-azure-sdk-for-ruby-0.6.8/lib/azure/base_management/base_management_service.rb:80:in `validate_configuration'
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/stuartpreston-azure-sdk-for-ruby-0.6.8/lib/azure/base_management/base_management_service.rb:33:in `initialize'
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/stuartpreston-azure-sdk-for-ruby-0.6.8/lib/azure/cloud_service_management/cloud_service_management_service.rb:21:in `initialize'
```
---
### Subscription not specified in driver, and subscription_id and management_credentials used via .chef/knife.rb (.pfx)
UNTESTED

---
### Subscription not specified in driver, and subscription_id and management_credentials used via .chef/knife.rb (.pem)
UNTESTED

---

**Comment by jkeiser** [comment]
Strange. I tested almost entirely with not specifying the subscription id in the driver url, and that was working for me. I'm curious about the differences in our json ...

**Comment by stuartpreston** [comment]
So it urns out I had specified management_credentials by accident (should be management_certificate) in my Chef config.  Also uncovered an issue with filename handling in the SDK for the non-in-memory certificates.  Having another go at testing this today.

**Comment by stuartpreston** [comment]
## Manual testing using stuartpreston-azure-sdk-for-ruby-0.6.9

Recipe used:
```ruby
require 'chef/provisioning/azure_driver'
with_driver 'azure'

machine 'pendev01app99' do
  machine_options :bootstrap_options => {
   :cloud_service_name => 'pendricacloud01',
      :storage_account_name => 'pendricastore01',
      :vm_size => 'Standard_D1',
      :location => 'North Europe'
    },
    :password => 'P2ssw0rd',
    :image_id => 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB' #optional
end
```

## Results

| Approach (credentials source) | Result: recipe with no subscription specified in driver | Result: recipe with correct subscription specified in driver |
|-----------------------------------------------------------|---------------------------------------------------------|--------------------------------------------------------------|
| ~/.azure/azureProfile.json only | PASS | FAIL (see 1) |
| my.publishsettings (azure_subscriptions set in client.rb) | PASS | FAIL (see 1) |
| my.pfx (azure_subscriptions set in client.rb) | PASS | FAIL (see 1) |
| my.pem (azure_subscriptions set in client.rb) | PASS | FAIL (see 1) |

### ref 1
Recipe used:
```ruby
require 'chef/provisioning/azure_driver'
with_driver 'azure:b6e7eee9-e4cd-41ae-8432-03ab624df016'
# with_driver 'azure'

machine 'pendev01app99' do
  machine_options :bootstrap_options => { 
   :cloud_service_name => 'pendricacloud01',
      :storage_account_name => 'pendricastore01',
      :vm_size => 'Standard_D1',
      :location => 'North Europe'
    },
    :password => 'P2ssw0rd',
    :image_id => 'b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server-20140927-en-us-30GB' #optional
end
```

Stack:
```
Generated at 2015-03-30 15:22:46 +0100
NoMethodError: machine[pendev01app99] (@recipe_files::/Users/SP/destroy-temp.rb line 5) had an error: NoMethodError: undefined method `[]' for nil:NilClass
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-azure-0.2.1/lib/chef/provisioning/azure_driver/driver.rb:44:in `canonicalize_url'
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provisioning.rb:71:in `driver_for_url'
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
/Users/SP/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-0.19/lib/chef/provider/machine.rb:102:in `new_driver'
```

Comment:
Looking at the code, the subscription hash is only set when the account_id is nil or empty.  If we set one in the driver, then subscription will be nil.  I guess we need to return [ driver_url, config ] in this case.

Code:
```
    def self.canonicalize_url(driver_url, config)
      scheme, account_id = driver_url.split(':', 2)
      if account_id.nil? || account_id.empty?
        subscription = Subscriptions.default_subscription(config)
        if !subscription
          raise "Driver #{driver_url} did not specify a subscription ID, and no default subscription was found.  Have you downloaded the Azure CLI and used `azure account download` and `azure account import` to set up Azure?  Alternately, you can set azure_subscriptions to [ { subscription_id: '...', management_credentials: ... }] in your Chef configuration."
        end
        config = Cheffish::MergedConfig.new({ azure_subscriptions: subscription }, config)
      end
      [ "#{scheme}:#{subscription[:subscription_id]}", config ]
    end
```

**Comment by stuartpreston** [comment]
This was merged as #25 from my fork with some fixes.

**Pull request closed without merging**
